name: Run e2e tests in docker compose

permissions:
  contents: read  # This is required for actions/checkout
  id-token: write  # This is required for authenticating with aws

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:
    secrets:
      PULLPREVIEW_GOVUK_NOTIFY_API_KEY:
        required: true
      SLACK_BOT_TOKEN:
        required: true
      TEMP_SLACK_CHANNEL_ID:
        required: true

  workflow_dispatch:
    secrets:
      PULLPREVIEW_GOVUK_NOTIFY_API_KEY:
        required: true
      SLACK_BOT_TOKEN:
        required: true
      TEMP_SLACK_CHANNEL_ID:
        required: true

jobs:

  e2e_tests_docker_compose:
    name: Run E2E tests against docker compose
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14.4

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true

      - name: Disable man-db triggers
        run: |
          # https://github.com/actions/runner-images/issues/10977
          # Disables man-db triggers, which have been a cause of huge (but variable) delays in github action jobs
          # completing; we're seeing pauses on this step of 120+ seconds in some rare cases.
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db

      - name: Install playwright browsers
        run: uv run --frozen playwright install --with-deps chromium

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@8cccb8c14b6500aaffebff1aa49c502c34d2e5e6 # v2.1.0

      - name: start chrome
        run: uv run --frozen pytest --e2e --tracing=retain-on-failure --browser chromium --screenshot=only-on-failure -k test_start_chrome

      - name: Setup certs
        run: |
          sudo apt-get update && sudo apt-get install -y mkcert libnss3-tools
          make certs
          echo "GOVUK_NOTIFY_API_KEY=$PULLPREVIEW_GOVUK_NOTIFY_API_KEY" >> .env
          echo "GOVUK_NOTIFY_DISABLE=False" >> .env
          echo "127.0.0.1       sso.communities.gov.localhost funding.communities.gov.localhost" | sudo tee -a /etc/hosts
        env:
          PULLPREVIEW_GOVUK_NOTIFY_API_KEY: ${{ secrets.PULLPREVIEW_GOVUK_NOTIFY_API_KEY }}

      - name: Build assets
        run: npm ci && npm run build

      - name: start docker compose
        env:
           ASSETS_VITE_LIVE_ENABLED: false
        run: docker compose -f docker-compose.yml up -d --wait

      - name: run e2e tests
        run: |
          uv run --frozen pytest --e2e --tracing=retain-on-failure --browser chromium --screenshot=only-on-failure -vv --durations=999 tests/e2e

      - name: stop docker compose
        if: always() # Ensure this runs even if the previous step fails
        run: docker compose -f docker-compose.yml down

      - name: Save test failure tracing
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ failure() }}
        with:
          name: playwright-traces
          path: test-results/*

  notify_slack:
    needs:
      - e2e_tests_docker_compose
    if: ${{ always() && (needs.e2e_tests_docker_compose.result == 'failure') && github.ref_name == 'main'}}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/notify-slack-deployment-failed.yml@d4a4c7d63b1d5c82a8c1fe57edea8ef529a60d04  # PR #313
    with:
      app_name: FS Docker Compose E2E Tests
      env_name: N/A
      github_username: ${{ github.actor }}
      workflow_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      compare_url: ${{ github.event_name == 'push' && github.event.compare || null }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_NOTIFICATION_CHANNEL_ID: ${{ secrets.TEMP_SLACK_CHANNEL_ID }}
