name: Run e2e tests

permissions:
  contents: read  # This is required for actions/checkout
  id-token: write  # This is required for authenticating with aws

on:
  workflow_call:
    inputs:
      environment:
        description: "Which AWS environment to test against."
        type: string
        required: true
        default: dev
    secrets:
      AWS_ACCOUNT:
        required: true
      SERVICE_ACCOUNT_USERNAME:
          required: true
      SERVICE_ACCOUNT_PASSWORD:
          required: true
  workflow_dispatch:
    inputs:
      environment:
        description:  Which AWS Account to use
        type: choice
        required: true
        options:
        - dev
        - test
    secrets:
      AWS_ACCOUNT:
        required: true
      SERVICE_ACCOUNT_USERNAME:
        required: true
      SERVICE_ACCOUNT_PASSWORD:
        required: true

jobs:
  e2e_tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14.4

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true

      - name: Disable man-db triggers
        run: |
          # https://github.com/actions/runner-images/issues/10977
          # Disables man-db triggers, which have been a cause of huge (but variable) delays in github action jobs
          # completing; we're seeing pauses on this step of 120+ seconds in some rare cases.
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db

      - name: Install playwright browsers
        run: uv run --frozen playwright install --with-deps chromium

      - name: Get current date
        shell: bash
        id: currentdatetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GithubCopilotDeploy
          role-session-name: "funding-service_test_${{ steps.currentdatetime.outputs.datetime }}"
          aws-region: eu-west-2

      - name: run e2e tests
        run: uv run --frozen pytest --e2e --e2e-env ${{ inputs.environment }} --tracing=retain-on-failure --browser chromium -vv --durations=999 tests/e2e
        env:
          SERVICE_ACCOUNT_USERNAME: ${{ secrets.SERVICE_ACCOUNT_USERNAME }}
          SERVICE_ACCOUNT_PASSWORD: ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}

      - name: Save test failure tracing
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: ${{ failure() }}
        with:
          name: playwright-traces
          path: test-results/*
